/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.minimal.schema;

import de.uni_koblenz.jgralab.impl.GraphFactoryImpl;

public class MinimalSchemaFactory extends GraphFactoryImpl {

	public MinimalSchemaFactory() {
		super();
		fillTable();
	}

	protected void fillTable() { 

		/* code for graph de.uni_koblenz.minimal.schema.MinimalGraph */
		setGraphImplementationClass(de.uni_koblenz.minimal.schema.MinimalGraph.class, de.uni_koblenz.minimal.schema.impl.std.MinimalGraphImpl.class);

		setVertexImplementationClass(de.uni_koblenz.minimal.schema.Node.class, de.uni_koblenz.minimal.schema.impl.std.NodeImpl.class);

		setEdgeImplementationClass(de.uni_koblenz.minimal.schema.Link.class, de.uni_koblenz.minimal.schema.impl.std.LinkImpl.class);

	}
}
