/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.minimal.schema.impl.std;

import de.uni_koblenz.jgralab.impl.std.EdgeImpl;

import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;
import de.uni_koblenz.jgralab.Vertex;

import de.uni_koblenz.minimal.schema.impl.std.ReversedLinkImpl;

import java.io.IOException;
/**
 * FromVertexClass: Node
 * FromRoleName : source
 * ToVertexClass: Node
 * ToRoleName : target
 */

public class LinkImpl extends EdgeImpl implements de.uni_koblenz.jgralab.Edge, de.uni_koblenz.minimal.schema.Link {

	public LinkImpl(int id, de.uni_koblenz.jgralab.Graph g, Vertex alpha, Vertex omega) {
		super(id, g, alpha, omega);
	}

	public final de.uni_koblenz.jgralab.schema.AttributedElementClass getAttributedElementClass() {
		return de.uni_koblenz.minimal.schema.MinimalSchema.instance().ec_Link;
	}

	public final java.lang.Class<? extends de.uni_koblenz.jgralab.AttributedElement> getM1Class() {
		return de.uni_koblenz.minimal.schema.Link.class;
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		throw new NoSuchFieldException("Link doesn't contain an attribute " + attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		throw new NoSuchFieldException("Link doesn't contain an attribute " + attributeName);
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException, NoSuchFieldException {
		throw new NoSuchFieldException("Link doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException, NoSuchFieldException {
		throw new NoSuchFieldException("Link doesn't contain an attribute " + attributeName);
	}

	public de.uni_koblenz.minimal.schema.Link getNextLinkInGraph() {
		return (de.uni_koblenz.minimal.schema.Link)getNextEdgeOfClassInGraph(de.uni_koblenz.minimal.schema.Link.class);
	}

	public de.uni_koblenz.minimal.schema.Link getNextLink() {
		return (de.uni_koblenz.minimal.schema.Link)getNextEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class);
	}

	public de.uni_koblenz.minimal.schema.Link getNextLink(EdgeDirection orientation) {
		return (de.uni_koblenz.minimal.schema.Link)getNextEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, orientation);
	}

	public de.uni_koblenz.jgralab.schema.AggregationKind getSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getAlphaSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	@Override
	public de.uni_koblenz.jgralab.schema.AggregationKind getOmegaSemantics() {
		return de.uni_koblenz.jgralab.schema.AggregationKind.NONE;
	}

	protected de.uni_koblenz.jgralab.impl.ReversedEdgeBaseImpl createReversedEdge() {
		return new ReversedLinkImpl(this, graph);
	}
}
