/*
 * This code was generated automatically.
 * Do NOT edit this file, changes will be lost.
 * Instead, change and commit the underlying schema.
 */

package de.uni_koblenz.minimal.schema.impl.std;

import de.uni_koblenz.jgralab.impl.IncidenceIterable;

import de.uni_koblenz.jgralab.impl.std.VertexImpl;

import de.uni_koblenz.jgralab.Edge;
import de.uni_koblenz.jgralab.EdgeDirection;
import de.uni_koblenz.jgralab.GraphIO;
import de.uni_koblenz.jgralab.GraphIOException;

import de.uni_koblenz.jgralab.schema.impl.DirectedM1EdgeClass;

import java.io.IOException;
import java.util.HashSet;
import java.util.Set;

public class NodeImpl extends VertexImpl implements de.uni_koblenz.minimal.schema.Node, de.uni_koblenz.jgralab.Vertex {

	protected java.lang.String _label;

	public NodeImpl(int id, de.uni_koblenz.jgralab.Graph g) {
		super(id, g);
	}

	public final de.uni_koblenz.jgralab.schema.AttributedElementClass getAttributedElementClass() {
		return de.uni_koblenz.minimal.schema.MinimalSchema.instance().vc_Node;
	}

	public final java.lang.Class<? extends de.uni_koblenz.jgralab.AttributedElement> getM1Class() {
		return de.uni_koblenz.minimal.schema.Node.class;
	}

	public Object getAttribute(String attributeName) throws NoSuchFieldException {
		if (attributeName.equals("label")) return get_label();
		throw new NoSuchFieldException("Node doesn't contain an attribute " + attributeName);
	}

	public void setAttribute(String attributeName, Object data) throws NoSuchFieldException {
		if (attributeName.equals("label")) {
			set_label((java.lang.String) data);
			return;
		}
		throw new NoSuchFieldException("Node doesn't contain an attribute " + attributeName);
	}

	public java.lang.String get_label() {
		return _label;
	}

	public void set_label(java.lang.String _label) {
		this._label = _label;
		graphModified();
	}

	public void readAttributeValues(GraphIO io) throws GraphIOException {
		_label = io.matchUtfString();
		set_label(_label);
	}

	public void readAttributeValueFromString(String attributeName, String value) throws GraphIOException, NoSuchFieldException {
		if (attributeName.equals("label")) {
			GraphIO io = GraphIO.createStringReader(value, getSchema());
			_label = io.matchUtfString();
			set_label(_label);
			return;
		}
		throw new NoSuchFieldException("Node doesn't contain an attribute " + attributeName);
	}

	public void writeAttributeValues(GraphIO io) throws GraphIOException, IOException {
		io.space();
		io.writeUtfString(_label);
	}

	public String writeAttributeValueToString(String attributeName) throws IOException, GraphIOException, NoSuchFieldException {
		if (attributeName.equals("label")) {
			GraphIO io = GraphIO.createStringWriter(getSchema());
			io.writeUtfString(_label);
			return io.getStringWriterResult();
		}
		throw new NoSuchFieldException("Node doesn't contain an attribute " + attributeName);
	}

	/* add all valid from edges */
	private static Set<java.lang.Class<? extends Edge>> validFromEdges = new HashSet<java.lang.Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidAlpha()
	 */
	@Override
	public boolean isValidAlpha(Edge edge) {
		return validFromEdges.contains(edge.getM1Class());
	}
	
	{

		validFromEdges.add(de.uni_koblenz.minimal.schema.Link.class);

	}
	
	/* add all valid to edges */
	private static Set<java.lang.Class<? extends Edge>> validToEdges = new HashSet<java.lang.Class<? extends Edge>>();
	
	/* (non-Javadoc)
	 * @see jgralab.Vertex:isValidOemga()
	 */
	@Override
	public boolean isValidOmega(Edge edge) {
		return validToEdges.contains(edge.getM1Class());
	}
	
	{

		validToEdges.add(de.uni_koblenz.minimal.schema.Link.class);

	}

	@Override
	public de.uni_koblenz.minimal.schema.Node getNextNode() {
		return (de.uni_koblenz.minimal.schema.Node)getNextVertexOfClass(de.uni_koblenz.minimal.schema.Node.class);
	}

	@Override
	public de.uni_koblenz.minimal.schema.Link getFirstLink() {
		return (de.uni_koblenz.minimal.schema.Link)getFirstEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class);
	}

	@Override
	public de.uni_koblenz.minimal.schema.Link getFirstLink(EdgeDirection orientation) {
		return (de.uni_koblenz.minimal.schema.Link)getFirstEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, orientation);
	}
		@Override
		public de.uni_koblenz.minimal.schema.Link add_source(de.uni_koblenz.minimal.schema.Node vertex) {
			return ((de.uni_koblenz.minimal.schema.MinimalGraph)getGraph()).createEdge(de.uni_koblenz.minimal.schema.Link.class, (de.uni_koblenz.minimal.schema.Node) vertex, (de.uni_koblenz.minimal.schema.Node) this);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.minimal.schema.Node> remove_source() {
			java.util.List<de.uni_koblenz.minimal.schema.Node> adjacences = new java.util.ArrayList<de.uni_koblenz.minimal.schema.Node>();
			de.uni_koblenz.minimal.schema.Link edge = (de.uni_koblenz.minimal.schema.Link) getFirstEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.minimal.schema.Link next = (de.uni_koblenz.minimal.schema.Link) edge.getNextEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.IN);
				adjacences.add((de.uni_koblenz.minimal.schema.Node) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_source(de.uni_koblenz.minimal.schema.Node vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.minimal.schema.Link edge = (de.uni_koblenz.minimal.schema.Link) getFirstEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.IN);
			while (edge != null) {
				de.uni_koblenz.minimal.schema.Link next = (de.uni_koblenz.minimal.schema.Link) edge.getNextEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.IN);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public Iterable<? extends de.uni_koblenz.minimal.schema.Node> get_source() {
			return new de.uni_koblenz.jgralab.impl.NeighbourIterable<de.uni_koblenz.minimal.schema.Link, de.uni_koblenz.minimal.schema.Node>(this, de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.IN);
		}
		@Override
		public de.uni_koblenz.minimal.schema.Link add_target(de.uni_koblenz.minimal.schema.Node vertex) {
			return ((de.uni_koblenz.minimal.schema.MinimalGraph)getGraph()).createEdge(de.uni_koblenz.minimal.schema.Link.class, (de.uni_koblenz.minimal.schema.Node) this, (de.uni_koblenz.minimal.schema.Node) vertex);
		}
		@Override
		public java.util.List<? extends de.uni_koblenz.minimal.schema.Node> remove_target() {
			java.util.List<de.uni_koblenz.minimal.schema.Node> adjacences = new java.util.ArrayList<de.uni_koblenz.minimal.schema.Node>();
			de.uni_koblenz.minimal.schema.Link edge = (de.uni_koblenz.minimal.schema.Link) getFirstEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.minimal.schema.Link next = (de.uni_koblenz.minimal.schema.Link) edge.getNextEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.OUT);
				adjacences.add((de.uni_koblenz.minimal.schema.Node) edge.getThat());
				edge.delete();
				edge = next;
			}
			return adjacences;
		}
		@Override
		public boolean remove_target(de.uni_koblenz.minimal.schema.Node vertex) {
			boolean elementRemoved = false;
			de.uni_koblenz.minimal.schema.Link edge = (de.uni_koblenz.minimal.schema.Link) getFirstEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.OUT);
			while (edge != null) {
				de.uni_koblenz.minimal.schema.Link next = (de.uni_koblenz.minimal.schema.Link) edge.getNextEdgeOfClass(de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.OUT);
				if (edge.getThat().equals(vertex)) {			edge.delete();
					elementRemoved = true;
				}
				edge = next;
			}
			return elementRemoved;
		}
		@Override
		public Iterable<? extends de.uni_koblenz.minimal.schema.Node> get_target() {
			return new de.uni_koblenz.jgralab.impl.NeighbourIterable<de.uni_koblenz.minimal.schema.Link, de.uni_koblenz.minimal.schema.Node>(this, de.uni_koblenz.minimal.schema.Link.class, EdgeDirection.OUT);
		}

	@Override
	public Iterable<de.uni_koblenz.minimal.schema.Link> getLinkIncidences() {
		return new IncidenceIterable<de.uni_koblenz.minimal.schema.Link>(this, de.uni_koblenz.minimal.schema.Link.class);
	}
	
	
	@Override
	public Iterable<de.uni_koblenz.minimal.schema.Link> getLinkIncidences(EdgeDirection direction) {
		return new IncidenceIterable<de.uni_koblenz.minimal.schema.Link>(this, de.uni_koblenz.minimal.schema.Link.class, direction);
	}

	private static java.util.Map<String, DirectedM1EdgeClass> roleMap;

	static {
	roleMap = new java.util.HashMap<String, DirectedM1EdgeClass>();

	roleMap.put("target", new DirectedM1EdgeClass(de.uni_koblenz.minimal.schema.Link.class, de.uni_koblenz.jgralab.EdgeDirection.OUT));

	roleMap.put("source", new DirectedM1EdgeClass(de.uni_koblenz.minimal.schema.Link.class, de.uni_koblenz.jgralab.EdgeDirection.IN));

	}

	public DirectedM1EdgeClass getEdgeForRolename(String rolename) {
		return roleMap.get(rolename);
	}
}
